"""Phase 6 Step 6 — the release gate.

Everything here is `integration`-marked and excluded from the fast suite, and
the spec is explicit that it is required before any release. Two tests, at two
scales:

**The micro-run.** Three agents, two rounds, real local inference — exactly what
the spec asks for. It proves the chain the whole project rests on: the local
model binding answers, OASIS builds a population from the files Phase 4 writes,
the broadcaster seeds the event, agents take real turns, and Step 3's round
bookkeeping attributes what they did.

**The pipeline.** `create` → `prepare` → `start` → complete through the service
layer, with a population generated by the model rather than handed in. Slower,
and worth it: driving this by hand is what found the event-loop deadlock in
Step 5, and a bug that only appears when the pieces are assembled is exactly
the kind a smoke test exists to catch.

Both use short temporary paths: the control socket is limited to 107
characters and pytest's own `tmp_path` can exhaust that on its own.
"""

from __future__ import annotations

import shutil
import sqlite3
import tempfile
import time
from pathlib import Path

import pytest

from app.services.oasis_profiles import write_profiles
from app.services.profile_generator import PersonaProfile
from app.services.simulation_config_generator import SimulationConfig
from app.services.simulation_manager import SimulationManager
from app.services.simulation_persistence import RunLedger
from app.services.simulation_runner import SimulationRunner
from app.services.simulation_store import SimulationState, SimulationStore

pytestmark = pytest.mark.integration

SCENARIO = {
    "graph_id": "smoke",
    "rounds": 2,
    "hours_per_round": 6,
    "event": "Riverbend Council published a draft housing density policy allowing "
             "four-storey development along the Eastgate corridor.",
    "broadcaster": {"name": "Riverbend Wire", "description": "Local news account"},
    "seed_posts": [{"content": "Council publishes draft density policy for Eastgate. "
                               "Four-storey development would be permitted."}],
    "scheduled_events": [{"round": 2, "description": "Developer rebuttal",
                          "content": "A developer group says the plan is too timid."}],
}

PEOPLE = [
    PersonaProfile(name="Dawn Mercer", age=41, occupation="carpenter",
                   activity_level="high", gender="female", country="United Kingdom",
                   background="Runs a small joinery on the Eastgate corridor.",
                   leanings="sceptical of developers"),
    PersonaProfile(name="Ray Nkemelu", age=33, occupation="bus driver",
                   activity_level="high", gender="male", country="United Kingdom",
                   background="Drives the Eastgate route six days a week.",
                   leanings="in favour of more housing"),
    PersonaProfile(name="Ursula Ferreira", age=67, occupation="full-time carer",
                   activity_level="high", gender="female", country="United Kingdom",
                   background="Has lived on the corridor for forty years.",
                   leanings="opposed"),
]


@pytest.fixture
def workspace():
    """A short-pathed working directory, removed however the test ends."""
    directory = Path(tempfile.mkdtemp(prefix="cs-smoke-", dir="/tmp"))
    yield directory
    shutil.rmtree(directory, ignore_errors=True)


def read_db(path):
    connection = sqlite3.connect(path)
    connection.row_factory = sqlite3.Row
    try:
        return {
            "users": connection.execute(
                "SELECT user_id, user_name FROM user").fetchall(),
            "posts": connection.execute(
                "SELECT post_id, user_id, content FROM post").fetchall(),
            "traces": connection.execute("SELECT action FROM trace").fetchall(),
        }
    finally:
        connection.close()


# ==========================================================================
# The micro-run the spec asks for
# ==========================================================================


async def test_three_agents_two_rounds_against_local_ollama(integration_config,
                                                             workspace):
    """The chain the whole project rests on, end to end and unmocked."""
    profiles = workspace / "profiles"
    write_profiles(PEOPLE, profiles, default_country="United Kingdom")

    config = SimulationConfig.model_validate(SCENARIO)
    config.scheduled_events[0].enabled = True  # an operator turned it on at review

    database = workspace / "simulation.db"
    ledger = RunLedger(database)
    runner = SimulationRunner(config, profiles, database,
                              config=integration_config, rng_seed=5)
    summaries = []
    try:
        await runner.setup()

        assert len(runner.population()) == 3, "three agents"
        assert runner.broadcaster is not None, "and an account to seed the event"
        assert runner.env.llm_semaphore._value == integration_config.LLM_CONCURRENCY

        ledger.ensure_schema()
        marks = ledger.marks()
        summaries.append(await runner.seed())
        ledger.record_round(_record(0, summaries[-1], ledger, marks))

        for index in (1, 2):
            marks = ledger.marks()
            summaries.append(await runner.run_round(index))
            ledger.record_round(_record(index, summaries[-1], ledger, marks))
    finally:
        await runner.close()

    # -- the run itself ----------------------------------------------------
    assert len(summaries) == 3, "a seed round and two simulated rounds"
    assert summaries[2].events_fired == 1, "the enabled event fired in its round"
    assert summaries[1].events_fired == 0, "and not before"
    assert sum(s.invoked for s in summaries[1:]) > 0, "agents took real turns"
    assert sum(s.failed for s in summaries) == 0, \
        f"agent turns failed: {[s.failures for s in summaries]}"

    # -- what it produced --------------------------------------------------
    data = read_db(database)
    assert len(data["users"]) == 4, "three agents plus the broadcaster"
    assert all(row["user_name"] for row in data["users"]), \
        "OASIS signs population agents up as NULL without our backfill"
    contents = [row["content"] or "" for row in data["posts"]]
    assert any("density policy" in text for text in contents), "the seed post"
    assert any("too timid" in text for text in contents), "the scheduled event"
    assert len(data["posts"]) > 2, "agents posted of their own accord"
    assert data["traces"], "actions were traced"

    # -- and that it can be described afterwards ---------------------------
    rounds = ledger.rounds()
    assert [r.round for r in rounds] == [0, 1, 2]
    assert any(r.action_counts for r in rounds), "per-action counts were recorded"

    by_round = ledger.posts_by_round()
    assert len(by_round[0]) >= 1, "the seed post is attributed to round zero"
    assert sum(len(ids) for ids in by_round.values()) == len(data["posts"]), \
        "every post belongs to exactly one round"

    progress = ledger.progress(total_rounds=2)
    assert progress["total_rounds"] == 2
    assert progress["action_counts"], "the run can report what the population did"


def _record(index, summary, ledger, marks_before):
    from app.services.simulation_persistence import RoundRecord

    return RoundRecord(
        round=index, invoked=summary.invoked, acted=summary.acted,
        failed=summary.failed, skipped=summary.skipped,
        events_fired=summary.events_fired,
        action_counts=ledger.action_counts(marks_before),
        failures=summary.failures,
    )


# ==========================================================================
# The whole pipeline, through the service layer
# ==========================================================================


async def test_create_prepare_start_completes_a_run(integration_config, workspace,
                                                     monkeypatch):
    """`create` → `prepare` → `start` → complete, with a model-built population.

    Slower than the micro-run and deliberately kept: assembling these pieces is
    what exposed the event-loop deadlock, and no unit test saw it.
    """
    from app.services.population import plan_population, sketch_population
    from app.services.profile_generator import EntityContext, ProfileGenerator
    from app.services.profile_job import generate_population
    from app.utils.llm_client import LLMClient

    settings = integration_config.model_copy(update={
        "MAX_CONCURRENT_SIMULATIONS": 2, "API_LLM_RESERVE": 1})
    store = SimulationStore(workspace / "simulations")
    manager = SimulationManager(store, config=settings)

    # ---- create ----------------------------------------------------------
    meta = store.create_pending(graph_id="smoke", platform="twitter", rounds=2,
                                total_agents=3)
    assert store.load_meta(meta.sim_id).state == SimulationState.DRAFT
    assert not store.prepared(meta.sim_id)

    # ---- prepare: a real population from the real model -------------------
    document = (
        "Riverbend City Council published a draft housing density policy on 14 "
        "March. Councillor Jane Doe, who chairs the Planning Committee, said the "
        "proposal would permit four-storey development along the Eastgate "
        "corridor. The Riverbend Residents Association objected that the "
        "twenty-one day consultation was inadequate."
    )
    llm = LLMClient(settings)
    try:
        sketch = await sketch_population(None, document, llm)
        generator = ProfileGenerator(settings, llm=llm)
        contexts = [EntityContext(uuid="e-1", name="Councillor Jane Doe",
                                  type="Person")]
        plan = plan_population(contexts, total=3, sketch=sketch,
                               generator=generator, named_ratio=0.34)

        seen: list[tuple[int, int]] = []
        result = await generate_population(
            generator, plan, store.profiles_dir(meta.sim_id),
            progress=lambda done, total, name: seen.append((done, total)))
        assert result.profiles, "the model produced no personas"
        assert seen and seen[-1][0] == seen[-1][1], "progress reached completion"

        bundle = write_profiles(result.profiles, store.profiles_dir(meta.sim_id))
        assert bundle.count == len(result.profiles)

        config = SimulationConfig.model_validate({**SCENARIO, "graph_id": "smoke"})
        store.save_config(meta.sim_id, config)
    finally:
        await llm.aclose()

    assert store.prepared(meta.sim_id)
    assert store.load_meta(meta.sim_id).state == SimulationState.DRAFT, \
        "preparing must not lock the configuration"

    # ---- start: a real process, supervised over its socket ----------------
    record = manager.start(meta.sim_id)
    assert record.pid > 0
    assert record.concurrency >= 1, "the worker was given a share of the budget"
    assert store.load_meta(meta.sim_id).state == SimulationState.RUNNING

    stages: list[str] = []
    deadline = time.time() + 900
    while time.time() < deadline:
        status = manager.status(meta.sim_id)
        if status.get("stage"):
            stages.append(status["stage"])
        if not status.get("running"):
            break
        time.sleep(1.0)

    assert stages, "no status ever came back from the worker"
    assert store.load_meta(meta.sim_id).state == SimulationState.COMPLETE, \
        f"run did not complete; stages seen: {stages}"

    # ---- what the run left behind ----------------------------------------
    ledger = RunLedger(store.sim_dir(meta.sim_id) / "simulation.db")
    assert [r.round for r in ledger.rounds()] == [0, 1, 2]

    data = read_db(store.sim_dir(meta.sim_id) / "simulation.db")
    assert len(data["users"]) == len(result.profiles) + 1, "population plus broadcaster"
    assert data["posts"], "nothing was posted"

    assert manager.capacity() == settings.MAX_CONCURRENT_SIMULATIONS, \
        "the slot was returned when the run finished"
    assert not (store.sim_dir(meta.sim_id) / "control.sock").exists(), \
        "the control socket was left behind"
